### ISSUE TITLE
🐛 Bug Report: the official libredd.it instance brings to a different website

### ISSUE THREAD

**Issue by ascreenwithlegs** [libreddit/libreddit#587]
## Describe the bug

  the offical instance at libredd.it instead of bringing to the libreddit interface brings to a "chatify" interface, the website is also been flagged as malicious on virustotal.com by "heimdal security"

**Comment by spikecodes** [comment]
Hi, I believe the issue was I didn't have auto-renew on so for a short period, libredd.it was owned by the registrar and used for marketing. It's good to go now though, just flooded with users that it never loads as usual...

![image](https://user-images.githubusercontent.com/19519553/199392366-0275ac05-f5d0-44a9-ba06-b0fbff1507a9.png)
