### ISSUE TITLE
🐛 Bug Report: Sorting by new is broken?

### ISSUE THREAD

**Issue by HumanityIncorporated** [libreddit/libreddit#601]
## Describe the bug
At least the first page of new-sort in user submissions page messes up sorting? 

## Steps to reproduce the bug

1. Go to https://libreddit.nl/user/jbkempf/submitted
"Sep 25 '13"
"Mar 18 '11"
"Sep 29 '17"
"May 01 '20"
etc.

## What's the expected behavior?
 Shouldn't new-sorting sort by year, then month, then date? Not sure what's going on here.

## Additional context / screenshot

![image](https://user-images.githubusercontent.com/113918897/196696977-6269ed66-f2e1-4c7e-8547-9d8676f87f24.png)

**Comment by spikecodes** [comment]
Hey @HumanityIncorporated, I see the issue. Libreddit is actually sorting by new correctly. The user simply set those first four posts you see as "pinned" on their user profile so that they always show at the top no matter what sort method you use. If you scroll down past those, you'll see every post/comment correctly in reverse chronological order.

On Reddit, these pinned posts are indicated with a green pin icon but I realize this wasn't clear on Libreddit so I've opened #606 to address this.

![image](https://user-images.githubusercontent.com/19519553/199389319-ec701919-6628-4513-acbe-7c02db5a88e7.png)

@stemid To set a default setting, you need to prepend the environment variable with `LIBREDDIT_DEFAULT_` so to set the default post sort method, use the environment variable `LIBREDDIT_DEFAULT_POST_SORT`.
