### ISSUE TITLE
🐛 Bug Report: aarch64 Docker builds have been failing for 6 months

### ISSUE THREAD

**Issue by tazz4843** [libreddit/libreddit#641]
Latest output logs: https://github.com/libreddit/libreddit/actions/runs/3466848096/jobs/5791127262.

Exit code 137 makes me think something was attacked by SIGKILL (137-128 = 9: SIGKILL), which is very likely the OOM reaper. Possible fix would be decreasing the concurrency for these builds (`-j 1` perhaps?). Not 100% sure as the logs are next to useless, so other input here is a good idea.

**Comment by Daniel-Valentine** [comment]
@spikecodes: I know you were looking into this a while back. Any update on this front?

**Comment by Daniel-Valentine** [comment]
(temporarily reopening; will close if/when fix is confirmed)

**Comment by Daniel-Valentine** [comment]
Per [this discussion](https://users.rust-lang.org/t/cargo-uses-too-much-memory-being-run-in-qemu/76531) on the Rust language forum, it appears Cargo's git library is consuming too many resources, specifically RAM, for Linux's liking. The solution is to tell cargo to use git the binary rather than a library.

[A build is underway](https://github.com/libreddit/libreddit/actions/runs/3527659829/jobs/5916958140). Hopefully, this goes through. If not, we may need to instruct cargo to execute only one job at a time. Unfortunately, this means the ARM Docker build will take even more time than it does now, which, given the VMs limited resources, is already a lot (the build started 30 minutes ago as of the time I wrote this comment).

I suspect this is a manifestation of rust-lang/cargo#10583. The config fix I mentioned above is also offered as a suggestion in [one of the comments for that issue](https://github.com/rust-lang/cargo/issues/10583#issuecomment-1129997984).

**Comment by Daniel-Valentine** [comment]
The build passed. I'm going to consider this fixed, but I'll keep my eye out to make sure we don't see this again. If we do, we may have to impose a cargo job limit of 1 as I said earlier.
