### ISSUE TITLE
💡 Feature request: empty front page

### ISSUE THREAD

**Issue by 100Roberts** [libreddit/libreddit#708]
## Is your feature request related to a problem? Please describe.

Reddit is an addictive and time-wasting website. 

## Describe the feature you would like to be implemented

In the settings page under interfaces, front page there should be a fourth option 'none' or 'disabled'

**Comment by spikecodes** [comment]
Hi, I think the use case for this is really specific (not a common enough request to change the code) but here's my recommended solution: follow a user who doesn't post. The default front page setting will show "No posts".

**Comment by 0-Il** [comment]
This is my biggest gripe with libreddit... every time I open the website, it loads a lot of content from either r/all or r/popular eating my traffic and slowing my browsing. I have to set `https://libreddit.kavin.rocks/settings` as my bookmark to load a relatively minimal page instead of loads of content I don't want to see. I also have another issue related to not having an option to choose a simple blank front page, but won't describe it here - it's too long. I really hope this feature will be implemented in future. I'm not complaining - the project is perfect otherwise.
