### ISSUE TITLE
repl unavailable

### ISSUE THREAD

**Issue by aqtsalt** [libreddit/libreddit#725]
on the hoempage 
![image](https://user-images.githubusercontent.com/104331720/219883592-6c3c1b20-8ee8-4600-921c-305b3278e64a.png)

**Comment by spikecodes** [comment]
Hi, sometimes the large amount of traffic stops Libreddit from loading for a single request. The fix for this is just doing a force-refresh.

**Comment by redactedscribe** [comment]
Hello @spikecodes. I've been receiving that error and:

```
Hmm... We couldn't reach this Repl
Make sure this Repl has a port open and is ready to receive HTTP traffic.
```

For quite a while (~2 months). Maybe a week or so after finding this project have I not been able to use it. I'm guessing it's since around the time that I opened an issue here, which happens to be the same date as this issue.

I've tried Ctrl+F5, clearing cookies and cache, and trying a different browser. All give me the same. Perhaps VPNs are being blocked?

**Comment by sigaloid** [comment]
It's possible replit is blocking VPN's - for this I recommend using a different instance. https://github.com/libreddit/libreddit-instances/blob/master/instances.md

**Comment by redactedscribe** [comment]
Thanks @sigaloid. The other instances seem to work fine. I guess it's a VPN issue.

**Comment by 06000208** [comment]
I'm currently getting this and I don't have a VPN. The page blank loads (doesn't respond to the request) for a minute or more before timing out with the error.
![image](https://user-images.githubusercontent.com/52764066/236099568-c04590e3-9776-4321-a555-88b9843a0075.png)
