### ISSUE TITLE
Remove Account from Libreddit

### ISSUE THREAD

**Issue by beyondthemoments** [libreddit/libreddit#777]
Please remove account u/beyondthemoments from libreddit. If you cannot remove the account, can you please delete all comments made within the account as well as all links included in the comments? Otherwise, I will have to report the site to Google since Google Search is viewing libreddit as a "toxic" site that is linking back to my site.

**Comment by beyondthemoments** [comment]
The issue is that the original question/string has been deleted from Reddit, yet all of the comments (including mine with a link) are still appearing on Libreddit. I am not able to edit anything on Libreddit, and these comments no longer exist on Reddit so I am not able to delete them from there.

**Comment by sigaloid** [comment]
If you've edited it out, the Libreddit instance will only cache that content for 5 minutes max. So if you visit one of the Libreddit sites after editing it, it should be evicted from the cache by now.

When you click the Google result and get led to the Libreddit site, does the original unedited comment appear? Or does it only appear in the Google preview text below the result?

If you click the link, and it's gone from the Libreddit site, but still shows up in the Google preview text, **this is a problem on Google's side for caching it.** At that point I recommend you to submit it to the [**Remove Outdated Content** tool](https://search.google.com/search-console/remove-outdated-content)

Side note: Libreddit is a software that some people choose to run on their server. There is no central "Libreddit" server (in fact there are dozens). Hence I can't really help you getting it removed from someone else's site. We've thought about the issue of deleted content and that's why we don't save stuff like that (even though unddit/reveddit perform the same service).

**Comment by sigaloid** [comment]
If it's no longer on reddit, though, it should no longer be on libreddit. It's possible the site has some additional caching layer, I suppose.

Do you have any specific links you would be willing to provide? I'd like to see why deleted content would still show up (shouldn't be possible).

**Comment by beyondthemoments** [comment]
Here is an example feed in which I commented and have a link included that I would like removed: https://reddit.catvibers.me/r/VisitingIceland/comments/uotb7v/how_much_can_one_explore_with_bad_knees/.

When I go to my profile on reddit, the comment I made on that feed does not appear, and thus I am not able to edit it.

**Comment by sigaloid** [comment]
When you visit this link directly, you cannot edit/remove the comment? https://reddit.com/r/VisitingIceland/comments/uotb7v/deleted_by_user/i8gyh7t/?context=3

**Comment by beyondthemoments** [comment]
No, there is no where to edit/remove the comment. I even tried clicking around on random things, but there is no way for me to edit/delete it.

**Comment by beyondthemoments** [comment]
I guess I could delete it from Reddit, but honestly I would like to leave it on Reddit and remove it only from libreddit. That is why I think I will have to disavow all links from libreddit.
