### ISSUE TITLE
🐛 Bug Report: Searching for posts no longer works 

### ISSUE THREAD

**Issue by Growebis** [libreddit/libreddit#842]
## Describe the bug
 I noticed today trying to search for posts on a subreddit no longer works and returns "No posts were found." This was working perfectly fine yesterday. I have tested various instances that are using the latest version of Libreddit and the problem persists. 

## Steps to reproduce the bug

1.  Be on a subreddit (doesn't matter which subreddit)
2.  Try to search for posts on said subreddit.
3.  You get "No posts were found."
## What's the expected behavior?
 to actually see posts from the search on said subreddit

## Additional context / screenshot

![image](https://github.com/libreddit/libreddit/assets/113867283/94fa6e71-24f0-4962-9ae0-cd3c9af339c5)
here searching for posts not on a subreddit also doesn't work
![image](https://github.com/libreddit/libreddit/assets/113867283/eddb73cf-8e37-4534-bff1-2cbdb1b4386d)
here is an example of trying to search for something but it doesn't work
instance used in the screenshots is https://libreddit.northboot.xyz

Perhaps Reddit changed something in the search?

**Comment by GitKepler** [comment]
I think the search feature is simply not working on reddit since earlier today.
E.g.
- https://libreddit.northboot.xyz/r/help/comments/1527yk6/searchs_dont_work_when_sorting_by_anything_other/
- https://libreddit.northboot.xyz/r/help/comments/152578k/unable_to_search_for_anything/
- https://libreddit.northboot.xyz/r/help/comments/151raxt/reddit_search_not_working/
- https://libreddit.northboot.xyz/r/help/comments/152527j/when_i_try_to_search_something_on_any_subreddit/

Trying to fetch search result using Reddit API returns nothing (`https://www.reddit.com/r/<subreddit>/search.rss?q=<search_query>`)

Both the rss, xml and json endpoints return nothing:

JSON endpoint result for `https://www.reddit.com/r/all/search.rss?q=test&restrict_sr=1`
```json
{"kind": "Listing", "data": {"modhash": "", "dist": 0, "facets": {}, "after": null, "geo_filter": "", "children": [], "before": null}}
```

XML and RSS endpoint results:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
    <category term="all" label="r/all" />
    <updated>2023-07-17T19:07:19+00:00</updated>
    <id>/r/all/search.xml?q=test&amp;restrict_sr=1</id>
    <link rel="self" href="https://www.reddit.com/r/all/search.xml?q=test&amp;restrict_sr=1"
        type="application/atom+xml" />
    <link rel="alternate" href="https://www.reddit.com/r/all/search?q=test&amp;restrict_sr=1"
        type="text/html" />
    <title>all: search results - test</title>
</feed>
```

**Comment by Growebis** [comment]
I guess i should have also tried to search in the reddit site to see if its also broken there. Anyways, i will close this unless the issue still stays on libreddit after reddit fixes the issue
